//checking
export const CHECKING_UP_COUNTER_STATUS = 'CHECKING_UP_COUNTER_STATUS';
export const CHECKING_OPEN = 'CHECKING_OPEN';
export const CHECKING_OTHER_CHANGES = 'CHECKING_OTHER_CHANGES';

//input
export const INPUT_SET_LOADED_FILE_DATA = 'INPUT_SET_LOADED_FILE_DATA';

//result
export const RESULT_SHOW = 'RESULT_SHOW';
export const RESULT_TOGGLE_ANON = 'RESULT_TOGGLE_ANON';
export const RESULT_TOGGLE_PROTOCOL = 'RESULT_TOGGLE_PROTOCOL';
export const RESULT_TOGGLE_COUNTRY = 'RESULT_TOGGLE_COUNTRY';
export const RESULT_TOGGLE_MISC = 'RESULT_TOGGLE_MISC';
export const RESULT_SET_SEARCH = 'RESULT_SET_SEARCH';
export const RESULT_LOAD_MORE = 'RESULT_LOAD_MORE';
export const RESULT_CLOSE = 'RESULT_CLOSE';
export const RESULT_TOGGLE_BLACKLIST = 'RESULT_TOGGLE_BLACKLIST';
export const RESULT_TOGGLE_COUNTRIES = 'RESULT_TOGGLE_COUNTRIES';
export const RESULT_SET_MAX_TIMEOUT = 'RESULT_SET_MAX_TIMEOUT';
export const RESULT_CHANGE_PORTS_INPUT = 'RESULT_CHANGE_PORTS_INPUT';
export const RESULT_SET_PORTS_ALLOW = 'RESULT_SET_PORTS_ALLOW';
export const RESULT_SORT = 'RESULT_SORT';
export const RESULT_EXPORT_TOGGLE = 'RESULT_EXPORT_TOGGLE';
export const RESULT_EXPORT_CHANGE_TYPE = 'RESULT_EXPORT_CHANGE_TYPE';
export const RESULT_EXPORT_CHANGE_AUTH_TYPE = 'RESULT_EXPORT_CHANGE_AUTH_TYPE';

//judges
export const JUDGES_CHANGE = 'JUDGES_CHANGE';
export const JUDGES_ADD = 'JUDGES_ADD';
export const JUDGES_REMOVE = 'JUDGES_REMOVE';
export const JUDGES_TOGGLE_OPTION = 'JUDGES_TOGGLE_OPTION';

//update
export const UPDATE_CHANGE_STATE = 'UPDATE_CHANGE_STATE';

//overlay ip
export const OVERLAY_IP_CHANGE_LOOKUP_STATUS = 'OVERLAY_IP_CHANGE_LOOKUP_STATUS';
export const OVERLAY_IP_CHANGE_LOOKUP_TO_INITIAL = 'OVERLAY_IP_CHANGE_LOOKUP_TO_INITIAL';

//overlay judges
export const OVERLAY_JUDGES_CHANGE_STATE = 'OVERLAY_JUDGES_CHANGE_STATE';
export const OVERLAY_JUDGE_CHANGE_PING_STATE = 'OVERLAY_JUDGE_CHANGE_PING_STATE';

//core
export const CORE_CHANGE_OPTION = 'CORE_CHANGE_OPTION';
export const CORE_TOGGLE_OPTION = 'CORE_TOGGLE_OPTION';
export const CORE_TOGGLE_PROTOCOL = 'CORE_TOGGLE_PROTOCOL';

//ip
export const IP_CHANGE_OPTION = 'IP_CHANGE_OPTION';
export const IP_SET = 'IP_SET';

//blacklist
export const BLACKLIST_CHANGE_ITEM_PATH = 'BLACKLIST_CHANGE_ITEM_PATH';
export const BLACKLIST_ADD_ITEM = 'BLACKLIST_ADD_ITEM';
export const BLACKLIST_REMOVE_ITEM = 'BLACKLIST_REMOVE_ITEM';
export const BLACKLIST_TOGGLE_OPTION = 'BLACKLIST_TOGGLE_OPTION';
export const BLACKLIST_SET_ACTIVE_ITEM = 'BLACKLIST_SET_ACTIVE_ITEM';

//main
export const MAIN_TOGGLE_DARK = 'MAIN_TOGGLE_DARK';
export const MAIN_SET_STATS = 'MAIN_SET_STATS';
