//checking
export const CHECKING_UP_COUNTER_STATUS = 'CHECKING_UP_COUNTER_STATUS';
export const CHECKING_OPEN = 'CHECKING_OPEN';
export const CHECKING_OTHER_CHANGES = 'CHECKING_OTHER_CHANGES';

//input
export const INPUT_SET_LOADED_FILE_DATA = 'INPUT_SET_LOADED_FILE_DATA';

//result
export const SHOW_RESULT = 'SHOW_RESULT';
export const TOGGLE_ANON = 'TOGGLE_ANON';
export const TOGGLE_PROTOCOL = 'TOGGLE_PROTOCOL';
export const TOGGLE_COUNTRY = 'TOGGLE_COUNTRY';
export const TOGGLE_MISC = 'TOGGLE_MISC';
export const SET_SEARCH = 'SET_SEARCH';
export const LOAD_MORE = 'LOAD_MORE';
export const RESULT_CLOSE = 'RESULT_CLOSE';
export const TOGGLE_BLACKLIST = 'TOGGLE_BLACKLIST';
export const RESULT_TOGGLE_COUNTRIES = 'RESULT_TOGGLE_COUNTRIES';
export const SET_MAX_TIMEOUT = 'SET_MAX_TIMEOUT';
export const CHANGE_PORTS_INPUT = 'CHANGE_PORTS_INPUT';
export const SET_PORTS_ALLOW = 'SET_PORTS_ALLOW';
export const RESULT_SORT = 'RESULT_SORT';
export const RESULT_EXPORT_TOGGLE = 'RESULT_EXPORT_TOGGLE';
export const RESULT_EXPORT_CHANGE_TYPE = 'RESULT_EXPORT_CHANGE_TYPE';

//judges
export const CHANGE_JUDGE = 'CHANGE_JUDGE';
export const ADD_JUDGE = 'ADD_JUDGE';
export const REMOVE_JUDGE = 'REMOVE_JUDGE';
export const TOGGLE_JUDGES_OPTION = 'TOGGLE_JUDGES_OPTION';

//update
export const CHANGE_UPDATE_STATE = 'CHANGE_UPDATE_STATE';

//overlay ip
export const OVERLAY_IP_CHANGE_LOOKUP_STATUS = 'OVERLAY_IP_CHANGE_LOOKUP_STATUS';
export const OVERLAY_IP_CHANGE_LOOKUP_TO_INITIAL = 'OVERLAY_IP_CHANGE_LOOKUP_TO_INITIAL';

//overlay judges
export const OVERLAY_JUDGES_CHANGE_STATE = 'OVERLAY_JUDGES_CHANGE_STATE';
export const OVERLAY_JUDGE_CHANGE_PING_STATE = 'OVERLAY_JUDGE_CHANGE_PING_STATE';

//core
export const CORE_CHANGE_OPTION = 'CORE_CHANGE_OPTION';
export const CORE_TOGGLE_OPTION = 'CORE_TOGGLE_OPTION';
export const CORE_TOGGLE_PROTOCOL = 'CORE_TOGGLE_PROTOCOL';

//ip
export const IP_CHANGE_OPTION = 'IP_CHANGE_OPTION';
export const IP_SET = 'IP_SET';

//blacklist
export const CHANGE_BLACKLIST_ITEM_PATH = 'CHANGE_BLACKLIST_ITEM_PATH';
export const ADD_BLACKLIST_ITEM = 'ADD_BLACKLIST_ITEM';
export const REMOVE_BLACKLIST_ITEM = 'REMOVE_BLACKLIST_ITEM';
export const TOGGLE_BLACKLIST_OPTION = 'TOGGLE_BLACKLIST_OPTION';
export const SET_ACTIVE_BLACKLIST_ITEM = 'SET_ACTIVE_BLACKLIST_ITEM';
